server:
  port: 8040
  ## 注册到服务中心的名字
spring:
  application:
    name: ribbon
## 注册中心的默认访问地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 ## 是否将微服务的Ip注册到服务中心上
  instance:
    prefer-ip-address: true