server:
  port: 8030
  ## 注册到服务中心的名字
spring:
  application:
    name: gateway
## 注册中心的默认访问地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
## 是否将微服务的Ip注册到服务中心上
  instance:
    prefer-ip-address: true
## 将注册中心叫provider的服务映射到的/p/** 的服务上（/P/a就可以访问到）
zuul:
  routes:
    provider: /p/**
